[2023-10-03T08:57:23.744+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: launches_getter.get_todays_launches manual__2023-10-03T08:57:20.700324+00:00 [queued]>
[2023-10-03T08:57:23.760+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: launches_getter.get_todays_launches manual__2023-10-03T08:57:20.700324+00:00 [queued]>
[2023-10-03T08:57:23.760+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T08:57:23.789+0000] {taskinstance.py:1350} INFO - Executing <Task(SimpleHttpOperator): get_todays_launches> on 2023-10-03 08:57:20.700324+00:00
[2023-10-03T08:57:23.796+0000] {standard_task_runner.py:57} INFO - Started process 1661 to run task
[2023-10-03T08:57:23.801+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'launches_getter', 'get_todays_launches', 'manual__2023-10-03T08:57:20.700324+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/launches.py', '--cfg-path', '/tmp/tmpbp78_b21']
[2023-10-03T08:57:23.802+0000] {standard_task_runner.py:85} INFO - Job 124: Subtask get_todays_launches
[2023-10-03T08:57:23.863+0000] {task_command.py:410} INFO - Running <TaskInstance: launches_getter.get_todays_launches manual__2023-10-03T08:57:20.700324+00:00 [running]> on host f21dc12153d8
[2023-10-03T08:57:23.933+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-10-03T08:57:23.986+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='launches_getter' AIRFLOW_CTX_TASK_ID='get_todays_launches' AIRFLOW_CTX_EXECUTION_DATE='2023-10-03T08:57:20.700324+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-03T08:57:20.700324+00:00'
[2023-10-03T08:57:23.986+0000] {http.py:123} INFO - Calling HTTP method
[2023-10-03T08:57:23.993+0000] {base.py:73} INFO - Using connection ID 'thespacedevs_dev' for task execution.
[2023-10-03T08:57:24.416+0000] {http.py:127} INFO - {"count":0,"next":null,"previous":null,"results":[]}
[2023-10-03T08:57:24.424+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 131, in execute
    raise AirflowException("Response check returned False.")
airflow.exceptions.AirflowException: Response check returned False.
[2023-10-03T08:57:24.428+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=launches_getter, task_id=get_todays_launches, execution_date=20231003T085720, start_date=20231003T085723, end_date=20231003T085724
[2023-10-03T08:57:24.445+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 124 for task get_todays_launches (Response check returned False.; 1661)
[2023-10-03T08:57:24.459+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T08:57:24.474+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
